### ISSUE TITLE
CreateModel failed with error code 15

### ISSUE THREAD

**Issue by sandeepbhutani304** [AdroitAnandAI/Indian-Accent-Speech-Recognition#2]
Very good article and I hope model should also be good. However, not able to run it due to some error. I have downloaded your model which you had put in this repo.  Please suggest:

`deepspeech --model output_graph_indian_test.pbmm --lm models/lm.binary --audio chunk02_speaker0_16.wav --alphabet models/alphabet.txt  --trie models/trie `

```
TensorFlow: v1.12.0-10-ge232881
DeepSpeech: v0.4.1-0-g0e40db6
Data loss: Corrupted memmapped model file: output_graph_indian_test.pbmm Invalid directory offset
Traceback (most recent call last):
  File "/anaconda3/envs/berttorchenv_dev/bin/deepspeech", line 8, in <module>
    sys.exit(main())
  File "/anaconda3/envs/berttorchenv_dev/lib/python3.6/site-packages/deepspeech/client.py", line 80, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/anaconda3/envs/berttorchenv_dev/lib/python3.6/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 15
```

**Comment by AdroitAnandAI** [comment]
This is caused by the corrupted memmapped model file: output_graph.pbmm uploaded to github via GIT LFS. The downloaded model in clones repo is around 200KB while the actual model is 180~190MB.

I have fixed it. Uploaded the trained model in google drive and gave the links in repo. Also added easy to use commands and hints in readme.txt. Please clone the repo again.

Hope it helps.
